[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[invariant]
runs = 2000
depth = 25
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true